### ISSUE TITLE
iOS configuration

### ISSUE THREAD

**Issue by colinhacks** [gunschu/jitsi_meet#11]
Just scanning this repo doing some initial research. I see that there is a section in the README for Android configuration but not for iOS. Is that because iOS doesn't require any additional configuration, or is it just not documented yet?

**Comment by buzzwin** [comment]
Good catch !There are permissions that need to be added for camera and audio into the info.plist file ... I will add those to the readme.


Sent from Yahoo Mail for iPhone


On Thursday, April 9, 2020, 10:02 PM, Colin McDonnell <notifications@github.com> wrote:




Just scanning this repo doing some initial research. I see that there is a section in the README for Android configuration but not for iOS. Is that because iOS doesn't require any additional configuration, or is it just not documented yet?

**Comment by colinhacks** [comment]
Thanks! Amazing work on this by the way 🙏

**Comment by dev2one** [comment]
@vriad did you manage to build it ? what is you Xcode version ? i have error on Xcode 11,4

**Comment by colinhacks** [comment]
@dev2one I haven't actually tried, I was just researching options when I created this issue. 

I think there are known bugs compiling the iOS SDK with XCode 11.4 (see [this issue](https://github.com/jitsi/jitsi-meet/issues/5645) created by the creator of this library). Someone posted a workaround that worked for them.

@buzzwin any more guidance on iOS configuration? Did the bug fix proposed in your other issue solve the 11.4 problem?

**Comment by buzzwin** [comment]
Jitsi developers have not bade any new releases so currently this plugin cannot be supported on Xcode 11.4 unless Jitsi start supporting their ark.So unfortunately the only option is to downgrade to Xcode 11.3 for now .


Sent from Yahoo Mail for iPhone


On Wednesday, April 15, 2020, 2:37 PM, Colin McDonnell <notifications@github.com> wrote:




I haven't actually tried, I was just researching options when I created this issue.

I think there are known bugs compiling the iOS SDK with XCode 11.4 (see this issue created by the creator of this library). Someone posted a workaround that worked for them.

@buzzwin any more guidance on iOS configuration? Did the bug fix proposed in your other issue solve the 11.4 problem?

**Comment by fagerbua** [comment]
@buzzwin @vriad The SDK builds fine in Xcode 11.4, but at the moment you'll need to build it yourself from source rather than using CocoaPods. I did the following:


```bash
$TARGET_PROJECT='directory of your project'
mkdir -p $TARGET_PROJECT/ManuallyBuiltFrameworks
git clone https://github.com/jitsi/jitsi-meet.git
cd jitsi-meet
npm install
(cd ios; pod install)
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

# Copy the built frameworks. the -H option is needed to follow the initial symlink.
cp -RH ios/sdk/JitsiMeet.framework node_modules/react-native-webrtc/ios/WebRTC.framework $TARGET_PROJECT/ManuallyBuiltFrameworks

# Strip bitcode - reducing file size by almost a gigabyte.
cd $TARGET_PROJECT/ManuallyBuiltFrameworks
xcrun bitcode_strip -r Frameworks/JitsiMeet.framework/JitsiMeet -o Frameworks/JitsiMeet.framework/JitsiMeet
xcrun bitcode_strip -r Frameworks/WebRTC.framework/WebRTC -o Frameworks/WebRTC.framework/WebRTC
```

Then in your own Xcode project, make sure the framework directories are added to the project and embedded in the build settings (Targets -> <Your app> -> General -> Frameworks, Libraries and Embedded Content)

**Comment by fagerbua** [comment]
@buzzwin @vriad Building from source on Xcode 11.4 (not using the cocoapod) is quite possible.  See https://github.com/jitsi/jitsi-meet/issues/5645#issuecomment-616073778.

**Comment by buzzwin** [comment]
v 0.1.8 has been published , these issues should be resolved .. you may have to run a pod update , pod repo update or re-run pod install on your project to upgrade to the new versions.
