### ISSUE TITLE
End meeting for all when Host ends the meeting.

### ISSUE THREAD

**Issue by jagadish-pattanaik** [gunschu/jitsi_meet#137]
**How to end meeting for all participants when the user ends the meeting**. Is it possible to do so or it needs a update? If it's possible then can anyone tell how to implement it?

**Comment by jimmyjose-dev** [comment]
End meeting for all is not supported ...as the concept of Host doesn't exist in Jitsi. 

That being said there is more than one way to achieve what you intend to do... it will be easier to share a solution if your setup is known... i will share two ways for now... 

_1)_ You are using **meet.jitsi server**
If you are using firebase firestore or something similar... 
you maintain a status for the room created for meeting.. 0 - for meeting didn't start.. 1 for ongoing meeting... 2 for meeting closed.
Using flutter provider(or whatever you like) everyone listens to this status... 

Use JitsiMeetingListener `onConferenceTerminated` check if thats your intended user(host) ..change the status of room to `2` .. write a logic that when the room status is 2 you call `JitsiMeet.closeMeeting();` it will close meeting for other users.

_2)_ You are using **your own server**
There is a prosody module which will check if there is no user with admin status then it will kill the room booting out all users and will gracefully terminate.

_PS: Since this is a prosody module there is no way for it to know that the admin/host closed due to network glitch or any other error.. so give the user benefit of doubt and allow 15-30 secs to rejoin before terminating._

**Comment by jagadish-pattanaik** [comment]
Thanks @Snapworks ...I will try it

**Comment by jagadish-pattanaik** [comment]
It's really difficult and not really a good decision to implement untill official SDK provides these features. But we can try what @Snapworks said. I am closing this issue here.
