### ISSUE TITLE
Please update sdk version 2.11.0

### ISSUE THREAD

**Issue by ShubhamJuIT** [gunschu/jitsi_meet#141]
few days ago probably, screen sharing feature is now available in android

**Comment by jimmyjose-dev** [comment]
We will be pushing an update, hopefully over this weekend...

**Comment by jagadish-pattanaik** [comment]
@Snapworks  Really? Are you saying that screen sharing in meeting will be available by this weekend??? I do really need that and waiting for it....

**Comment by jimmyjose-dev** [comment]
I tried their screen sharing feature, it works but lags a bit.. few tests and we should have it hopefully by this Sunday.

**Comment by jagadish-pattanaik** [comment]
Are you sure by this Sunday ?? Because i was gonna release update tonight I just stopped after seeing this and i have to release this update as soon as possible. So sure by Sunday? Bcz i am waiting for it...

And yes would you like to tell what more features you are gonna add? like avatar url, help button disabled like that?

Please add the following in this update with screen sharing:
- YouTube video share, lobby and help to features flag
- user avatar URL to meeting options

and yes please by Sunday....

**Comment by jimmyjose-dev** [comment]
@jagadish-pattanaik userAvatar has been merged thanks to contribution from @NVQuan , Screen sharing has been pushed and should be released today or tomorrow, if you don't wanna wait, you may go ahead and use the PR link mentioned above.

Feature flags might take longer than usual and may not be done by Sunday.
