### ISSUE TITLE
[FEATURE]: <Mute all participants (Video and Audio>

### ISSUE THREAD

**Issue by legaciespanda** [gunschu/jitsi_meet#291]
Please i want a feature that allows moderator  to mute all participant video and audio.

**Comment by jagadish-pattanaik** [comment]
@legaciespanda I guess it's already there, check it, mute everyone, disable everyone's video, mute everyone except one.

**Comment by legaciespanda** [comment]
@jagadish-pattanaik I can't find it. I'm not sure it's there.can you give me a code sample. Or show me where to find it?

**Comment by jagadish-pattanaik** [comment]
@legaciespanda click on the more options of the meeting and then scroll it up to open it full, you can find mute everyone, disable everyone's video options there and if you long tap on a user avatar or click in the more option on a user avatar you can find options mute everyone except one or disables everyone's video except.

if you can not find these then pls make sure you are using the latest plugin and jitsi SDK, because this is not related to code.
