### ISSUE TITLE
Enable and Disable call end button for specific user 

### ISSUE THREAD

**Issue by Ankit0080** [gunschu/jitsi_meet#339]
According to my requirement i have 2 things which i want to implement in the app but not able to find these kind of functuionality in the app

1. I want the the call enable and diasable to button to be hidden for specific users which i want.  At the time of meeting joining i want the host to decide whether the new joinee would be able to end the call or not I want to disable the meeting end button for that particular user.

2. Meeting Duration option is not there . At the time of meeting start there should be an option for meeting duration. If i decided meeting duration should be 10 minutes then after 10 minutes meeting will be close automatically

**Comment by devprajeet** [comment]
My Flutter app crashed when click call end button jitsi meeting.

Log below

 View class com.facebook.react.views.text.ReactTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils( 8021): View class com.facebook.react.views.switchview.ReactSwitch is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/unknown:ViewManager( 8021): Error while updating prop thumbTintColor
E/unknown:ViewManager( 8021): java.lang.reflect.InvocationTargetException
E/unknown:ViewManager( 8021): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager( 8021): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
E/unknown:ViewManager( 8021): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
E/unknown:ViewManager( 8021): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
E/unknown:ViewManager( 8021): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
E/unknown:ViewManager( 8021): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
E/unknown:ViewManager( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
E/unknown:ViewManager( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
E/unknown:ViewManager( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943)
E/unknown:ViewManager( 8021): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
E/unknown:ViewManager( 8021): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
E/unknown:ViewManager( 8021): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
E/unknown:ViewManager( 8021): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
E/unknown:ViewManager( 8021): 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
E/unknown:ViewManager( 8021): 	at android.view.Choreographer.doFrame(Choreographer.java:721)
E/unknown:ViewManager( 8021): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
E/unknown:ViewManager( 8021): 	at android.os.Handler.handleCallback(Handler.java:883)
E/unknown:ViewManager( 8021): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/unknown:ViewManager( 8021): 	at android.os.Looper.loop(Looper.java:214)
E/unknown:ViewManager( 8021): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/unknown:ViewManager( 8021): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager( 8021): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/unknown:ViewManager( 8021): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/unknown:ViewManager( 8021): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
E/unknown:ViewManager( 8021): 	at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51)
E/unknown:ViewManager( 8021): 	at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60)
E/unknown:ViewManager( 8021): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134)
E/unknown:ViewManager( 8021): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129)
E/unknown:ViewManager( 8021): 	... 23 more
D/AndroidRuntime( 8021): Shutting down VM
D/com.oney.WebRTCModule.VideoTrackAdapter( 8021): Deleted adapter for 8ebdeb3a-adbe-4558-96f0-43795a238b7e-10
D/com.oney.WebRTCModule.VideoTrackAdapter( 8021): Deleted adapter for mixedlabelvideo0
E/AndroidRuntime( 8021): FATAL EXCEPTION: main
E/AndroidRuntime( 8021): Process: com.wtf.member, PID: 8021
E/AndroidRuntime( 8021): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'thumbTintColor' of a view managed by: AndroidSwitch
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943)
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
E/AndroidRuntime( 8021): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
E/AndroidRuntime( 8021): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
E/AndroidRuntime( 8021): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
E/AndroidRuntime( 8021): 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
E/AndroidRuntime( 8021): 	at android.view.Choreographer.doFrame(Choreographer.java:721)
E/AndroidRuntime( 8021): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
E/AndroidRuntime( 8021): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8021): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8021): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8021): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 8021): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8021): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 8021): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 8021): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 8021): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8021): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
E/AndroidRuntime( 8021): 	... 21 more
E/AndroidRuntime( 8021): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
E/AndroidRuntime( 8021): 	at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51)
E/AndroidRuntime( 8021): 	at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60)
E/AndroidRuntime( 8021): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134)
E/AndroidRuntime( 8021): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129)
E/AndroidRuntime( 8021): 	... 23 more
E/JitsiMeetSDK( 8021): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK( 8021): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'thumbTintColor' of a view managed by: AndroidSwitch
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
E/JitsiMeetSDK( 8021): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
E/JitsiMeetSDK( 8021): 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
E/JitsiMeetSDK( 8021): 	at android.view.Choreographer.doFrame(Choreographer.java:721)
E/JitsiMeetSDK( 8021): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
E/JitsiMeetSDK( 8021): 	at android.os.Handler.handleCallback(Handler.java:883)
E/JitsiMeetSDK( 8021): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/JitsiMeetSDK( 8021): 	at android.os.Looper.loop(Looper.java:214)
E/JitsiMeetSDK( 8021): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/JitsiMeetSDK( 8021): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 8021): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/JitsiMeetSDK( 8021): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/JitsiMeetSDK( 8021): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK( 8021): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
E/JitsiMeetSDK( 8021): 	... 21 more
E/JitsiMeetSDK( 8021): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
E/JitsiMeetSDK( 8021): 	at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129)
E/JitsiMeetSDK( 8021): 	... 23 more
E/JitsiMeetSDK( 8021): 
E/JitsiMeetSDK( 8021): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'thumbTintColor' of a view managed by: AndroidSwitch
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
E/JitsiMeetSDK( 8021): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOpe

**Comment by devprajeet** [comment]
> My Flutter app crashed when click call end button jitsi meeting.
> 
> Log below
> 
> View class com.facebook.react.views.text.ReactTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant). E/ThemeUtils( 8021): View class com.facebook.react.views.switchview.ReactSwitch is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant). E/unknown:ViewManager( 8021): Error while updating prop thumbTintColor E/unknown:ViewManager( 8021): java.lang.reflect.InvocationTargetException E/unknown:ViewManager( 8021): at java.lang.reflect.Method.invoke(Native Method) E/unknown:ViewManager( 8021): at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83) E/unknown:ViewManager( 8021): at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134) E/unknown:ViewManager( 8021): at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54) E/unknown:ViewManager( 8021): at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48) E/unknown:ViewManager( 8021): at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278) E/unknown:ViewManager( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179) E/unknown:ViewManager( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972) E/unknown:ViewManager( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943) E/unknown:ViewManager( 8021): at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28) E/unknown:ViewManager( 8021): at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174) E/unknown:ViewManager( 8021): at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84) E/unknown:ViewManager( 8021): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964) E/unknown:ViewManager( 8021): at android.view.Choreographer.doCallbacks(Choreographer.java:790) E/unknown:ViewManager( 8021): at android.view.Choreographer.doFrame(Choreographer.java:721) E/unknown:ViewManager( 8021): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951) E/unknown:ViewManager( 8021): at android.os.Handler.handleCallback(Handler.java:883) E/unknown:ViewManager( 8021): at android.os.Handler.dispatchMessage(Handler.java:100) E/unknown:ViewManager( 8021): at android.os.Looper.loop(Looper.java:214) E/unknown:ViewManager( 8021): at android.app.ActivityThread.main(ActivityThread.java:7356) E/unknown:ViewManager( 8021): at java.lang.reflect.Method.invoke(Native Method) E/unknown:ViewManager( 8021): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) E/unknown:ViewManager( 8021): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) E/unknown:ViewManager( 8021): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference E/unknown:ViewManager( 8021): at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51) E/unknown:ViewManager( 8021): at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60) E/unknown:ViewManager( 8021): at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134) E/unknown:ViewManager( 8021): at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129) E/unknown:ViewManager( 8021): ... 23 more D/AndroidRuntime( 8021): Shutting down VM D/com.oney.WebRTCModule.VideoTrackAdapter( 8021): Deleted adapter for 8ebdeb3a-adbe-4558-96f0-43795a238b7e-10 D/com.oney.WebRTCModule.VideoTrackAdapter( 8021): Deleted adapter for mixedlabelvideo0 E/AndroidRuntime( 8021): FATAL EXCEPTION: main E/AndroidRuntime( 8021): Process: com.wtf.member, PID: 8021 E/AndroidRuntime( 8021): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'thumbTintColor' of a view managed by: AndroidSwitch E/AndroidRuntime( 8021): at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98) E/AndroidRuntime( 8021): at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134) E/AndroidRuntime( 8021): at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54) E/AndroidRuntime( 8021): at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48) E/AndroidRuntime( 8021): at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278) E/AndroidRuntime( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179) E/AndroidRuntime( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972) E/AndroidRuntime( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943) E/AndroidRuntime( 8021): at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28) E/AndroidRuntime( 8021): at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174) E/AndroidRuntime( 8021): at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84) E/AndroidRuntime( 8021): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964) E/AndroidRuntime( 8021): at android.view.Choreographer.doCallbacks(Choreographer.java:790) E/AndroidRuntime( 8021): at android.view.Choreographer.doFrame(Choreographer.java:721) E/AndroidRuntime( 8021): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951) E/AndroidRuntime( 8021): at android.os.Handler.handleCallback(Handler.java:883) E/AndroidRuntime( 8021): at android.os.Handler.dispatchMessage(Handler.java:100) E/AndroidRuntime( 8021): at android.os.Looper.loop(Looper.java:214) E/AndroidRuntime( 8021): at android.app.ActivityThread.main(ActivityThread.java:7356) E/AndroidRuntime( 8021): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime( 8021): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) E/AndroidRuntime( 8021): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) E/AndroidRuntime( 8021): Caused by: java.lang.reflect.InvocationTargetException E/AndroidRuntime( 8021): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime( 8021): at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83) E/AndroidRuntime( 8021): ... 21 more E/AndroidRuntime( 8021): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference E/AndroidRuntime( 8021): at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51) E/AndroidRuntime( 8021): at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60) E/AndroidRuntime( 8021): at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134) E/AndroidRuntime( 8021): at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129) E/AndroidRuntime( 8021): ... 23 more E/JitsiMeetSDK( 8021): JitsiMeetUncaughtExceptionHandler FATAL ERROR E/JitsiMeetSDK( 8021): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'thumbTintColor' of a view managed by: AndroidSwitch E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28) E/JitsiMeetSDK( 8021): at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174) E/JitsiMeetSDK( 8021): at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84) E/JitsiMeetSDK( 8021): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964) E/JitsiMeetSDK( 8021): at android.view.Choreographer.doCallbacks(Choreographer.java:790) E/JitsiMeetSDK( 8021): at android.view.Choreographer.doFrame(Choreographer.java:721) E/JitsiMeetSDK( 8021): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951) E/JitsiMeetSDK( 8021): at android.os.Handler.handleCallback(Handler.java:883) E/JitsiMeetSDK( 8021): at android.os.Handler.dispatchMessage(Handler.java:100) E/JitsiMeetSDK( 8021): at android.os.Looper.loop(Looper.java:214) E/JitsiMeetSDK( 8021): at android.app.ActivityThread.main(ActivityThread.java:7356) E/JitsiMeetSDK( 8021): at java.lang.reflect.Method.invoke(Native Method) E/JitsiMeetSDK( 8021): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) E/JitsiMeetSDK( 8021): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) E/JitsiMeetSDK( 8021): Caused by: java.lang.reflect.InvocationTargetException E/JitsiMeetSDK( 8021): at java.lang.reflect.Method.invoke(Native Method) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83) E/JitsiMeetSDK( 8021): ... 21 more E/JitsiMeetSDK( 8021): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference E/JitsiMeetSDK( 8021): at com.facebook.react.views.switchview.ReactSwitch.setColor(ReactSwitch.java:51) E/JitsiMeetSDK( 8021): at com.facebook.react.views.switchview.ReactSwitch.setThumbColor(ReactSwitch.java:60) E/JitsiMeetSDK( 8021): at com.facebook.react.views.switchview.ReactSwitchManager.setThumbColor(ReactSwitchManager.java:134) E/JitsiMeetSDK( 8021): at com.facebook.react.views.switchview.ReactSwitchManager.setThumbTintColor(ReactSwitchManager.java:129) E/JitsiMeetSDK( 8021): ... 23 more E/JitsiMeetSDK( 8021): E/JitsiMeetSDK( 8021): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'thumbTintColor' of a view managed by: AndroidSwitch E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:278) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972) E/JitsiMeetSDK( 8021): at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOpe

any please help , its urgent

**Comment by StowZ** [comment]
> According to my requirement i have 2 things which i want to implement in the app but not able to find these kind of functuionality in the app
> 
> 1. I want the the call enable and diasable to button to be hidden for specific users which i want.  At the time of meeting joining i want the host to decide whether the new joinee would be able to end the call or not I want to disable the meeting end button for that particular user.
> 2. Meeting Duration option is not there . At the time of meeting start there should be an option for meeting duration. If i decided meeting duration should be 10 minutes then after 10 minutes meeting will be close automatically

Any update I want to do the same thing but I can't find a way to do it ?
