### ISSUE TITLE
Participants list is not visible in jitsi flutter library.

### ISSUE THREAD

**Issue by Meri994** [gunschu/jitsi_meet#365]
I have downloaded the jitsi meet application from the AppStore and check the option for participants. From where I can find all participants list but in this library in menu option participants list is missing.

If the user is not able to see current participants in the meeting then it is not a user-friendly library.

Kindly add this option to the menu.

**Comment by Meri994** [comment]
Anyone from the contributors please check on this else jitsi in flutter is not useful. And there is not any way to get participants' info if any participant joins or drops the call. I hope I will get a sooner response on this. Thank you. @rwbr @jimmyjose-dev @agfeo @mosleim @tuantvu @jimmyjose-dev

**Comment by jimmyjose-dev** [comment]
Hi @MeriGarala09,
Since you have tagged me twice I guess I need to address this first :)
You are correct, currently, this feature doesn't exist in this package. Another user had posted a similar use case (around a year ago, you would have to dig through the issue list) and I had addressed this there with a few approaches on how this can be achieved. 

Maybe my other peers whom you have tagged would be able to suggest something better.
