### ISSUE TITLE
Can we close Jitsi meeting room programatically?

### ISSUE THREAD

**Issue by nvamsi214** [gunschu/jitsi_meet#39]
Hi, 
How can we stop the meeting call pragmatically on an event.

**Comment by TBG-FR** [comment]
Hi,

Maybe you can use `getJitsiView().leave()`, for example in `JitsiMeetPluginActivity.kt` ? 
You can check what I did with that here https://github.com/gunschu/jitsi_meet/commit/8d04e54e0e74a7d53b36e35cd7feefb504292f14
And the official reference (events, methods) here : [Android SDK (Jitsi Meet Handbook)](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk) : 

> leave()
Leaves the currently active conference. If the welcome page is enabled it will go back to it, otherwise a black window will be shown.

I don't know if this will fit your needs, tell me !
