### ISSUE TITLE
In the meeting keyboard opening issue in ios devices.

### ISSUE THREAD

**Issue by asghar-sohail** [gunschu/jitsi_meet#46]
I appreciate the hard work behind the library. and i am very thankful to the team who have made Flutter Jitsi Meet.
We are facing an issue. inside meeting when we click any button Camera, mic, menu and invite others the keyboard opens before dialog. this issue occurring only in ios devices. Android devices are working fine.
We need to publish the app as soon as possible.
Thanks

**Comment by rwbr** [comment]
Are you able to reproduce this issue with the example app? I had a similar problem, but it did not happen in the example. So I concluded, that it must have something’s do with my app’s  architecture. In the end I found out, that it was caused by an TextField in the underlying widget, that got the focus. When I disabled it before navigating to the next view, the problem was solved.

**Comment by asghar-sohail** [comment]
Alright
Thats helped me.
Thanks
