### ISSUE TITLE
Flutter web support.

### ISSUE THREAD

**Issue by NayanVerma10** [gunschu/jitsi_meet#66]
This package does does not support flutter web so what may I do for web and is there any chance that web support will be integrated in this package ?

**Comment by tuantvu** [comment]
That's a good question. This plugin is built on top of the Jitsi Mobile SDK, so not appropriate for the web. I have not worked with Flutter Web nor the Jitsi web yet. If there's a way for Flutter Web to exclude the Jitsi SDK from this plugin on compiling/publishing, without too much maintenance, then maybe we support the web version of Jitsi with it. If not, then a separate plugin would be better.

**Comment by lennhv** [comment]
Hi, i have the idea to implement the plugin for web support, but to keep that in this project we need to change the repository structure to commit cross-platform support recommended by flutter.

Pleas check the repository structure for url_launcher plugin:
https://github.com/flutter/plugins/tree/master/packages/url_launcher

I have the modifications in my machine 
![Screen Shot 2020-07-19 at 14 29 29](https://user-images.githubusercontent.com/24727511/87883371-8465d900-c9cc-11ea-8e62-207dc10c0443.png)

I will try to do the web plugin, but the proposed changes are important for the maintenance of the project.

**Comment by lennhv** [comment]
Hi @tuantvu, i implemented a web support for Jitsi based in your plugin, to do that i was forced to change flutter implementation in the plugin, basically restructure the plugin code and send some part to another plugin called `jitsi_meet_platform_interface` to allow cross-platform implementations, after that i implemented the web support called `jitsi_meet_web`. At this point i think can be another ways to integrate the web support.

Please take a time to review this first approach and give me a feedback, i interested contributing in your project in the best way.

All code is in https://github.com/lennhv/jitsi_meet_plugin (a clone of your plugin)

Regards

**Comment by tuantvu** [comment]
Thanks for taking the time to look into this. I'll try to take a look when I can. I will also need to take some time to study flutter web itself. Could you tell me if we move to this, would it be a breaking change?

**Comment by lennhv** [comment]
Hi, @tuantvu ,  from the plugin user point of view,  only change the way that import `JitsiMeetingOptions`, `JitsiMeetingResponse`, `JitsiMeetingListener`, `FeatureFlagHelper`, `FeatureFlagEnum`, because now are available when import the main package (`import 'package:jitsi_meet/jitsi_meet.dart';`)

But from the point of view of plugin source code I was forced to change some things by moving it to the `platform interface` plugin, it could be considered a breaking change.

**Comment by jagadish-pattanaik** [comment]
@tuantvu @lennhv @Snapworks I don't want to change any code for mobile and just wanna add the flutter web support for jitsi meet. How can I do that and is it production ready? And yes please tell such a method in which I don't have to change code for mobile.

**Comment by gunschu** [comment]
@lennhv just got to looking at your code , are you still up for making a pull request to add web support ?

**Comment by lennhv** [comment]
@gunschu sure, we can talk about how is the best way to integrate it because i remember your project has a different structure.

**Comment by gunschu** [comment]
@lennhv Since you are following the guidance on federated plugins and thats what we want to do in the future , I think we are open to restructuring the project as you have suggested. of course this will be a big change. We can create a major release in a branch . Can add you as a contributor if you are interested. Also you can send an email at gunschumentoring@gmail.com and we can coordinate.

**Comment by buzzwin** [comment]
@lennhv have created a new branch web and checked in refactored federated code. Facing issues with iframe rendering . If you would like to ccocntribute or help troubleshoot , please let us know.

**Comment by lennhv** [comment]
Hi @buzzwin sure, please add me as contributor.
